# Generated by Django 4.2.16 on 2024-10-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='jobprofile',
            name='job_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
